####
DROP TABLE PART;
CREATE TABLE PART ( P_PARTKEY INTEGER, P_NAME VARCHAR(55), P_MFGR CHAR(25), P_BRAND CHAR(10), P_TYPE VARCHAR(25), P_SIZE INTEGER, P_CONTAINER CHAR(10), P_RETAILPRICE DECIMAL, P_COMMENT VARCHAR(23));

DROP TABLE SUPPLIER;
CREATE TABLE SUPPLIER ( S_SUPPKEY Integer, S_NAME CHAR(25), S_ADDRESS VARCHAR(40), S_NATIONKEY INTEGER NOT NULL, S_PHONE CHAR(15), S_ACCTBAL DECIMAL, S_COMMENT VARCHAR(101));

DROP TABLE PARTSUPP;
CREATE TABLE PARTSUPP ( PS_PARTKEY INTEGER NOT NULL, PS_SUPPKEY INTEGER NOT NULL, PS_AVAILQTY INTEGER, PS_SUPPLYCOST DECIMAL, PS_COMMENT VARCHAR(199));

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER ( C_CUSTKEY Integer, C_NAME VARCHAR(25), C_ADDRESS VARCHAR(40), C_NATIONKEY INTEGER, C_PHONE CHAR(15), C_ACCTBAL DECIMAL, C_MKTSEGMENT CHAR(10), C_COMMENT VARCHAR(117));

DROP TABLE ORDERS;
CREATE TABLE ORDERS ( O_ORDERKEY Integer, O_CUSTKEY INTEGER NOT NULL, O_ORDERSTATUS CHAR(1), O_TOTALPRICE DECIMAL, O_ORDERDATE DATE, O_ORDERPRIORITY CHAR(15), O_CLERK CHAR(15), O_SHIPPRIORITY INTEGER, O_COMMENT VARCHAR(79));

DROP TABLE LINEITEM;
CREATE TABLE LINEITEM (L_ORDERKEY INTEGER NOT NULL,L_PARTKEY INTEGER NOT NULL,L_SUPPKEY INTEGER NOT NULL,L_LINENUMBER INTEGER,L_QUANTITY DECIMAL,L_EXTENDEDPRICE DECIMAL,L_DISCOUNT DECIMAL,L_TAX DECIMAL,L_RETURNFLAG CHAR(1),L_LINESTATUS CHAR(1),L_SHIPDATE DATE,L_COMMITDATE DATE,L_RECEIPTDATE DATE,L_SHIPINSTRUCT CHAR(25),L_SHIPMODE CHAR(10),L_COMMENT VARCHAR(44));

DROP TABLE NATION;
CREATE TABLE NATION (N_NATIONKEY Integer,N_NAME CHAR(25),N_REGIONKEY INTEGER NOT NULL,N_COMMENT VARCHAR(152));

DROP TABLE REGION;
CREATE TABLE REGION (R_REGIONKEY Integer,R_NAME CHAR(25),R_COMMENT VARCHAR(152));


####  WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE PART;
CREATE TABLE PART ( P_PARTKEY INTEGER, P_NAME VARCHAR(55), P_MFGR CHAR(25), P_BRAND CHAR(10), P_TYPE VARCHAR(25), P_SIZE INTEGER, P_CONTAINER CHAR(10), P_RETAILPRICE DECIMAL, P_COMMENT VARCHAR(23)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE SUPPLIER;
CREATE TABLE SUPPLIER ( S_SUPPKEY Integer, S_NAME CHAR(25), S_ADDRESS VARCHAR(40), S_NATIONKEY INTEGER NOT NULL, S_PHONE CHAR(15), S_ACCTBAL DECIMAL, S_COMMENT VARCHAR(101)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE PARTSUPP;
CREATE TABLE PARTSUPP ( PS_PARTKEY INTEGER NOT NULL, PS_SUPPKEY INTEGER NOT NULL, PS_AVAILQTY INTEGER, PS_SUPPLYCOST DECIMAL, PS_COMMENT VARCHAR(199)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER ( C_CUSTKEY Integer, C_NAME VARCHAR(25), C_ADDRESS VARCHAR(40), C_NATIONKEY INTEGER, C_PHONE CHAR(15), C_ACCTBAL DECIMAL, C_MKTSEGMENT CHAR(10), C_COMMENT VARCHAR(117)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE ORDERS;
CREATE TABLE ORDERS ( O_ORDERKEY Integer, O_CUSTKEY INTEGER NOT NULL, O_ORDERSTATUS CHAR(1), O_TOTALPRICE DECIMAL, O_ORDERDATE DATE, O_ORDERPRIORITY CHAR(15), O_CLERK CHAR(15), O_SHIPPRIORITY INTEGER, O_COMMENT VARCHAR(79)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE LINEITEM;
CREATE TABLE LINEITEM (L_ORDERKEY INTEGER NOT NULL,L_PARTKEY INTEGER NOT NULL,L_SUPPKEY INTEGER NOT NULL,L_LINENUMBER INTEGER,L_QUANTITY DECIMAL,L_EXTENDEDPRICE DECIMAL,L_DISCOUNT DECIMAL,L_TAX DECIMAL,L_RETURNFLAG CHAR(1),L_LINESTATUS CHAR(1),L_SHIPDATE DATE,L_COMMITDATE DATE,L_RECEIPTDATE DATE,L_SHIPINSTRUCT CHAR(25),L_SHIPMODE CHAR(10),L_COMMENT VARCHAR(44)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE NATION;
CREATE TABLE NATION (N_NATIONKEY Integer,N_NAME CHAR(25),N_REGIONKEY INTEGER NOT NULL,N_COMMENT VARCHAR(152)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

DROP TABLE REGION;
CREATE TABLE REGION (R_REGIONKEY Integer,R_NAME CHAR(25),R_COMMENT VARCHAR(152)) WITH BLOCKPROPERTIES (TYPE split_rowstore);

####  WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT ID, COMPRESS ALL);

DROP TABLE PART;
CREATE TABLE PART ( P_PARTKEY INTEGER, P_NAME VARCHAR(55), P_MFGR CHAR(25), P_BRAND CHAR(10), P_TYPE VARCHAR(25), P_SIZE INTEGER, P_CONTAINER CHAR(10), P_RETAILPRICE DECIMAL, P_COMMENT VARCHAR(23)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT P_PARTKEY, COMPRESS ALL);

DROP TABLE SUPPLIER;
CREATE TABLE SUPPLIER ( S_SUPPKEY Integer, S_NAME CHAR(25), S_ADDRESS VARCHAR(40), S_NATIONKEY INTEGER NOT NULL, S_PHONE CHAR(15), S_ACCTBAL DECIMAL, S_COMMENT VARCHAR(101)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT S_SUPPKEY, COMPRESS ALL);

DROP TABLE PARTSUPP;
CREATE TABLE PARTSUPP ( PS_PARTKEY INTEGER NOT NULL, PS_SUPPKEY INTEGER NOT NULL, PS_AVAILQTY INTEGER, PS_SUPPLYCOST DECIMAL, PS_COMMENT VARCHAR(199)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT PS_PARTKEY, COMPRESS ALL);

DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER ( C_CUSTKEY Integer, C_NAME VARCHAR(25), C_ADDRESS VARCHAR(40), C_NATIONKEY INTEGER, C_PHONE CHAR(15), C_ACCTBAL DECIMAL, C_MKTSEGMENT CHAR(10), C_COMMENT VARCHAR(117)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT C_CUSTKEY, COMPRESS ALL);

DROP TABLE ORDERS;
CREATE TABLE ORDERS ( O_ORDERKEY Integer, O_CUSTKEY INTEGER NOT NULL, O_ORDERSTATUS CHAR(1), O_TOTALPRICE DECIMAL, O_ORDERDATE DATE, O_ORDERPRIORITY CHAR(15), O_CLERK CHAR(15), O_SHIPPRIORITY INTEGER, O_COMMENT VARCHAR(79)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT O_ORDERKEY, COMPRESS ALL);

DROP TABLE LINEITEM;
CREATE TABLE LINEITEM (L_ORDERKEY INTEGER NOT NULL,L_PARTKEY INTEGER NOT NULL,L_SUPPKEY INTEGER NOT NULL,L_LINENUMBER INTEGER,L_QUANTITY DECIMAL,L_EXTENDEDPRICE DECIMAL,L_DISCOUNT DECIMAL,L_TAX DECIMAL,L_RETURNFLAG CHAR(1),L_LINESTATUS CHAR(1),L_SHIPDATE DATE,L_COMMITDATE DATE,L_RECEIPTDATE DATE,L_SHIPINSTRUCT CHAR(25),L_SHIPMODE CHAR(10),L_COMMENT VARCHAR(44)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT L_ORDERKEY, COMPRESS ALL);

DROP TABLE NATION;
CREATE TABLE NATION (N_NATIONKEY Integer,N_NAME CHAR(25),N_REGIONKEY INTEGER NOT NULL,N_COMMENT VARCHAR(152)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT N_NATIONKEY, COMPRESS ALL);

DROP TABLE REGION;
CREATE TABLE REGION (R_REGIONKEY Integer,R_NAME CHAR(25),R_COMMENT VARCHAR(152)) WITH BLOCKPROPERTIES (TYPE compressed_columnstore, SORT R_REGIONKEY, COMPRESS ALL);

